### ISSUE TITLE
getSequences should be able to return objects

### ISSUE THREAD

**Issue by cjmyers** [goksel/libSBOLj3#7]
It would be useful to have a getSequences methods that returns a list of Sequence objects.  This would require the URIs to be dereferenced within the document.

In libSBOLj, this was accomplished by making each object have an SBOLDocument field that indicated which SBOLDocument it is a member of.

**Comment by goksel** [comment]
The doc.getIdentified method provides a generic approach to return an object using its uri. Examples:
Sequence seq=doc.getIdentified(sequenceURI, Sequence.class);
Component comp=doc2.getIdentified(componentURI, Component.class);
