### ISSUE TITLE
Nice to have getSequenceByEncoding(Encoding.NucleicAcid)

### ISSUE THREAD

**Issue by cjmyers** [goksel/libSBOLj3#8]
This would search sequences and find the one matching an encoding.

**Comment by goksel** [comment]
Added component.getSequences(Encoding encoding) and document.getSequences(Encoding encoding) methods.

Added the following method on all Identifieds as a generic approach to filter properties of an Identified object:
 filterIdentifieds(List<URI> identifieds, URI property, String value)

Added the following on SBOLDocument as a generic approach to filter Toplevels by any property:	
filterIdentifiedItems(List<T> identifieds, URI property, String value)
